#pragma once

namespace carlos {
    //NOTE: Naming conflict with #define DELETE on Windows

    /// @brief Represents keys on the keyboard.
    /// @note Note for Key::DELETE_KEY, we were forced to append "_KEY" at the end of it,
    ///     because Windows has a macro define as DELETE, which was conflicting with our enum definition.
    enum class Key {
        UNKNOWN             = -1,                   //#define GLFW_KEY_UNKNOWN              -1
        SPACE               = 32,                   //#define GLFW_KEY_SPACE                32
        APOSTROPHE          = 39,                   //#define GLFW_KEY_APOSTROPHE           39
        COMMA               = 44,                   //#define GLFW_KEY_COMMA                44
        MINUS               = 45,                   //#define GLFW_KEY_MINUS                45
        PERIOD              = 46,                   //#define GLFW_KEY_PERIOD               46
        SLASH               = 47,                   //#define GLFW_KEY_SLASH                47
        ALPHA0              = 48,                   //#define GLFW_KEY_0                    48
        ALPHA1              = 49,                   //#define GLFW_KEY_1                    49
        ALPHA2              = 50,                   //#define GLFW_KEY_2                    50
        ALPHA3              = 51,                   //#define GLFW_KEY_3                    51
        ALPHA4              = 52,                   //#define GLFW_KEY_4                    52
        ALPHA5              = 53,                   //#define GLFW_KEY_5                    53
        ALPHA6              = 54,                   //#define GLFW_KEY_6                    54
        ALPHA7              = 55,                   //#define GLFW_KEY_7                    55
        ALPHA8              = 56,                   //#define GLFW_KEY_8                    56
        ALPHA9              = 57,                   //#define GLFW_KEY_9                    57
        SEMICOLON           = 59,                   //#define GLFW_KEY_SEMICOLON            59
        EQUAL               = 61,                   //#define GLFW_KEY_EQUAL                61
        A                   = 65,                   //#define GLFW_KEY_A                    65
        B                   = 66,                   //#define GLFW_KEY_B                    66
        C                   = 67,                   //#define GLFW_KEY_C                    67
        D                   = 68,                   //#define GLFW_KEY_D                    68
        E                   = 69,                   //#define GLFW_KEY_E                    69
        F                   = 70,                   //#define GLFW_KEY_F                    70
        G                   = 71,                   //#define GLFW_KEY_G                    71
        H                   = 72,                   //#define GLFW_KEY_H                    72
        I                   = 73,                   //#define GLFW_KEY_I                    73
        J                   = 74,                   //#define GLFW_KEY_J                    74
        K                   = 75,                   //#define GLFW_KEY_K                    75
        L                   = 76,                   //#define GLFW_KEY_L                    76
        M                   = 77,                   //#define GLFW_KEY_M                    77
        N                   = 78,                   //#define GLFW_KEY_N                    78
        O                   = 79,                   //#define GLFW_KEY_O                    79
        P                   = 80,                   //#define GLFW_KEY_P                    80
        Q                   = 81,                   //#define GLFW_KEY_Q                    81
        R                   = 82,                   //#define GLFW_KEY_R                    82
        S                   = 83,                   //#define GLFW_KEY_S                    83
        T                   = 84,                   //#define GLFW_KEY_T                    84
        U                   = 85,                   //#define GLFW_KEY_U                    85
        V                   = 86,                   //#define GLFW_KEY_V                    86
        W                   = 87,                   //#define GLFW_KEY_W                    87
        X                   = 88,                   //#define GLFW_KEY_X                    88
        Y                   = 89,                   //#define GLFW_KEY_Y                    89
        Z                   = 90,                   //#define GLFW_KEY_Z                    90
        LEFT_BRACKET        = 91,                   //#define GLFW_KEY_LEFT_BRACKET         91
        BACKSLASH           = 92,                   //#define GLFW_KEY_BACKSLASH            92
        RIGHT_BRACKET       = 93,                   //#define GLFW_KEY_RIGHT_BRACKET        93
        GRAVE_ACCENT        = 96,                   //#define GLFW_KEY_GRAVE_ACCENT         96
        // WORLD_1             = 161,                  //#define GLFW_KEY_WORLD_1              161 /* non-US #1 */
        // WORLD_2             = 162,                  //#define GLFW_KEY_WORLD_2              162 /* non-US #2 */
        ESCAPE              = 256,                  //#define GLFW_KEY_ESCAPE               256
        ENTER               = 257,                  //#define GLFW_KEY_ENTER                257
        TAB                 = 258,                  //#define GLFW_KEY_TAB                  258
        BACKSPACE           = 259,                  //#define GLFW_KEY_BACKSPACE            259
        INSERT              = 260,                  //#define GLFW_KEY_INSERT               260
        DELETE_KEY          = 261,                  //#define GLFW_KEY_DELETE               261
        RIGHT_ARROW         = 262,                  //#define GLFW_KEY_RIGHT                262
        LEFT_ARROW          = 263,                  //#define GLFW_KEY_LEFT                 263
        DOWN_ARROW          = 264,                  //#define GLFW_KEY_DOWN                 264
        UP_ARROW            = 265,                  //#define GLFW_KEY_UP                   265
        PAGE_UP             = 266,                  //#define GLFW_KEY_PAGE_UP              266
        PAGE_DOWN           = 267,                  //#define GLFW_KEY_PAGE_DOWN            267
        HOME                = 268,                  //#define GLFW_KEY_HOME                 268
        END                 = 269,                  //#define GLFW_KEY_END                  269
        CAPS_LOCK           = 280,                  //#define GLFW_KEY_CAPS_LOCK            280
        SCROLL_LOCK         = 281,                  //#define GLFW_KEY_SCROLL_LOCK          281
        NUM_LOCK            = 282,                  //#define GLFW_KEY_NUM_LOCK             282
        PRINT_SCREEN        = 283,                  //#define GLFW_KEY_PRINT_SCREEN         283
        PAUSE               = 284,                  //#define GLFW_KEY_PAUSE                284
        F1                  = 290,                  //#define GLFW_KEY_F1                   290
        F2                  = 291,                  //#define GLFW_KEY_F2                   291
        F3                  = 292,                  //#define GLFW_KEY_F3                   292
        F4                  = 293,                  //#define GLFW_KEY_F4                   293
        F5                  = 294,                  //#define GLFW_KEY_F5                   294
        F6                  = 295,                  //#define GLFW_KEY_F6                   295
        F7                  = 296,                  //#define GLFW_KEY_F7                   296
        F8                  = 297,                  //#define GLFW_KEY_F8                   297
        F9                  = 298,                  //#define GLFW_KEY_F9                   298
        F10                 = 299,                  //#define GLFW_KEY_F10                  299
        F11                 = 300,                  //#define GLFW_KEY_F11                  300
        F12                 = 301,                  //#define GLFW_KEY_F12                  301
        F13                 = 302,                  //#define GLFW_KEY_F13                  302
        F14                 = 303,                  //#define GLFW_KEY_F14                  303
        F15                 = 304,                  //#define GLFW_KEY_F15                  304
        F16                 = 305,                  //#define GLFW_KEY_F16                  305
        F17                 = 306,                  //#define GLFW_KEY_F17                  306
        F18                 = 307,                  //#define GLFW_KEY_F18                  307
        F19                 = 308,                  //#define GLFW_KEY_F19                  308
        F20                 = 309,                  //#define GLFW_KEY_F20                  309
        F21                 = 310,                  //#define GLFW_KEY_F21                  310
        F22                 = 311,                  //#define GLFW_KEY_F22                  311
        F23                 = 312,                  //#define GLFW_KEY_F23                  312
        F24                 = 313,                  //#define GLFW_KEY_F24                  313
        F25                 = 314,                  //#define GLFW_KEY_F25                  314
        NUMPAD0             = 320,                  //#define GLFW_KEY_KP_0                 320
        NUMPAD1             = 321,                  //#define GLFW_KEY_KP_1                 321
        NUMPAD2             = 322,                  //#define GLFW_KEY_KP_2                 322
        NUMPAD3             = 323,                  //#define GLFW_KEY_KP_3                 323
        NUMPAD4             = 324,                  //#define GLFW_KEY_KP_4                 324
        NUMPAD5             = 325,                  //#define GLFW_KEY_KP_5                 325
        NUMPAD6             = 326,                  //#define GLFW_KEY_KP_6                 326
        NUMPAD7             = 327,                  //#define GLFW_KEY_KP_7                 327
        NUMPAD8             = 328,                  //#define GLFW_KEY_KP_8                 328
        NUMPAD9             = 329,                  //#define GLFW_KEY_KP_9                 329
        NUMPAD_DECIMAL      = 330,                  //#define GLFW_KEY_KP_DECIMAL           330
        NUMPAD_DIVIDE       = 331,                  //#define GLFW_KEY_KP_DIVIDE            331
        NUMPAD_MULTIPLY     = 332,                  //#define GLFW_KEY_KP_MULTIPLY          332
        NUMPAD_SUBTRACT     = 333,                  //#define GLFW_KEY_KP_SUBTRACT          333
        NUMPAD_ADD          = 334,                  //#define GLFW_KEY_KP_ADD               334
        NUMPAD_ENTER        = 335,                  //#define GLFW_KEY_KP_ENTER             335
        NUMPAD_EQUALS       = 336,                  //#define GLFW_KEY_KP_EQUAL             336
        LEFT_SHIFT          = 340,                  //#define GLFW_KEY_LEFT_SHIFT           340
        LEFT_CONTROL        = 341,                  //#define GLFW_KEY_LEFT_CONTROL         341
        LEFT_ALT            = 342,                  //#define GLFW_KEY_LEFT_ALT             342
        LEFT_SUPER          = 343,                  //#define GLFW_KEY_LEFT_SUPER           343
        RIGHT_SHIFT         = 344,                  //#define GLFW_KEY_RIGHT_SHIFT          344
        RIGHT_CONTROL       = 345,                  //#define GLFW_KEY_RIGHT_CONTROL        345
        RIGHT_ALT           = 346,                  //#define GLFW_KEY_RIGHT_ALT            346
        RIGHT_SUPER         = 347,                  //#define GLFW_KEY_RIGHT_SUPER          347
        MENU                = 348,                  //#define GLFW_KEY_MENU                 348

        FIRST               = SPACE,
        LAST                = MENU                  //#define GLFW_KEY_LAST                 GLFW_KEY_MENU
    };
}
